### PR TITLE
Moved preventDefault() to include 'enter' and 'space' keys.

### PR DESCRIPTION
**Pull request by svinkle**
I was using this yesterday and had to adjust for 'enter' key press as well. Let's simplify and move `preventDefault()` to inside the `code` conditional statement.

Thoughts @ginader @karlgroves?

### CODE REVIEW

**Comment by ginader** [comment]
I was considering this as well but couldn't get verification if preventing the Enter default might be breaking something. You are very likely to be right here though. Karl?

**Comment by karlgroves** [comment]
Preventing enter default is likely to have negative ramifications for certain controls.  I mean, it largely depends on the use case.  For instance, if you're binding to a custom control then this makes sense.  But if you're binding something to like a checkbox it might prevent the checkbox from setting its 'checked' state.

**Comment by ginader** [comment]
:+1:

**Comment by svinkle** [comment]
Agreed, the purpose of this utility is to aid in accessibility for non-semantic elements. I assume that someone would know not to use this on a native control, such as a checkbox.

Are we saying no to this merge because we can't assume proper usage? Or should this include `preventDefault()` at all, let the dev handle this in their own event handlers?

**Comment by karlgroves** [comment]
True. I suppose you can't protect against consumer stupidity.  Even in the
case I mentioned, they should be doing something smarter like checking for
the checked state.

I say merge.

On Mon, Mar 2, 2015 at 11:38 AM, Scott Vinkle notifications@github.com
wrote:

> Agreed, the purpose of this utility is to aid in accessibility for
> non-semantic elements. I assume that someone would know not to use this on
> a native control, such as a checkbox.
> 
> Are we saying no to this merge because we can't assume proper usage? Or
> should this include preventDefault() at all, let the dev handle this in
> their own event handlers?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/svinkle/a11yclick/pull/3#issuecomment-76794360.

## 

Karl Groves
www.karlgroves.com
@karlgroves
http://www.linkedin.com/in/karlgroves
Phone: +1 410.541.6829

Modern Web Toolsets and Accessibility
https://www.youtube.com/watch?v=_uq6Db47-Ks

www.tenon.io

**Comment by ginader** [comment]
Do it Karl! :-)

**Comment by karlgroves** [comment]
That'll have to be @svinkle 
"Only those with write access to this repository can merge pull requests."  ;-)

**Comment by ginader** [comment]
Ah! I keep forgetting that this is not your Repo @karlgroves — Merge it @svinkle :+1:

**Comment by svinkle** [comment]
Thanks for your valuable input and time guys!

**Pull request merged**
